   [build]
   builder = "nixpacks"
   buildCommand = "dotnet publish -c Release -o out"

   [deploy]
   startCommand = "dotnet out/DMS.dll"
   healthcheckPath = "/"
   healthcheckTimeout = 100

   [variables]
   NIXPACKS_DOTNET_SDK_VERSION = "8.0"